server:
  port: 8089

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false  #关闭检查
        namespace: ${server.spring.profiles.active=public} #获取配置中心中对应命名空间的信息
    sentinel:
      transport:
        dashboard: localhost:9999
      eager: true

