spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
          Resource-Service:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000 #ms
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true

