server:
  port: 80   #localhost 默认80端口

spring:
  profiles:
    include: route
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  data: #redis
    redis:
      port: 6379
      password: 123456
      host: localhost
      database: 0




