server:
  port: 8020
spring:
  application:
    name: Login-Service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  data:
    redis:
      port: 6379
      password: 123456
      host: localhost
      database: 0



feign:
  sentinel:
    enabled: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

